[2024-07-24T03:36:55.450+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=etl_reddit_pipeline/run_id=manual__2024-07-24T03:36:48.207881+00:00/task_id=upload_s3 permission to 509
[2024-07-24T03:36:55.451+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=etl_reddit_pipeline/run_id=manual__2024-07-24T03:36:48.207881+00:00/task_id=upload_s3 permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_reddit_pipeline/run_id=manual__2024-07-24T03:36:48.207881+00:00/task_id=upload_s3'
[2024-07-24T03:36:55.475+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=etl_reddit_pipeline/run_id=manual__2024-07-24T03:36:48.207881+00:00/task_id=upload_s3 permission to 509
[2024-07-24T03:36:55.476+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=etl_reddit_pipeline/run_id=manual__2024-07-24T03:36:48.207881+00:00/task_id=upload_s3 permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_reddit_pipeline/run_id=manual__2024-07-24T03:36:48.207881+00:00/task_id=upload_s3'
[2024-07-24T03:36:55.512+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.upload_s3 manual__2024-07-24T03:36:48.207881+00:00 [queued]>
[2024-07-24T03:36:55.525+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.upload_s3 manual__2024-07-24T03:36:48.207881+00:00 [queued]>
[2024-07-24T03:36:55.525+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-24T03:36:55.543+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_s3> on 2024-07-24 03:36:48.207881+00:00
[2024-07-24T03:36:55.557+0000] {standard_task_runner.py:57} INFO - Started process 69 to run task
[2024-07-24T03:36:55.559+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'upload_s3', 'manual__2024-07-24T03:36:48.207881+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpexq6wmls']
[2024-07-24T03:36:55.561+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask upload_s3
[2024-07-24T03:36:55.615+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=etl_reddit_pipeline/run_id=manual__2024-07-24T03:36:48.207881+00:00/task_id=upload_s3 permission to 509
[2024-07-24T03:36:55.616+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=etl_reddit_pipeline/run_id=manual__2024-07-24T03:36:48.207881+00:00/task_id=upload_s3 permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_reddit_pipeline/run_id=manual__2024-07-24T03:36:48.207881+00:00/task_id=upload_s3'
[2024-07-24T03:36:55.618+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.upload_s3 manual__2024-07-24T03:36:48.207881+00:00 [running]> on host a3b014fcf0aa
[2024-07-24T03:36:55.694+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ibrahim Fazili' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='upload_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T03:36:48.207881+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-24T03:36:48.207881+00:00'
[2024-07-24T03:36:56.276+0000] {logging_mixin.py:151} INFO - Bucket already exists:  if-reddit-engineering
[2024-07-24T03:36:56.277+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 14, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/')[-1])
  File "/opt/airflow/etls/aws_etl.py", line 42, in upload_to_s3
    s3.put(file_path, bucket + '/raw/' + s3 , s3_file_name)
TypeError: can only concatenate str (not "S3FileSystem") to str
[2024-07-24T03:36:56.292+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=upload_s3, execution_date=20240724T033648, start_date=20240724T033655, end_date=20240724T033656
[2024-07-24T03:36:56.303+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task upload_s3 (can only concatenate str (not "S3FileSystem") to str; 69)
[2024-07-24T03:36:56.334+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-24T03:36:56.355+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
